#
# Copyright 2011-2018 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx#license-bsd-2-clause
#

BGFX_DIR=..
RUNTIME_DIR=$(BGFX_DIR)/runtime
BUILD_DIR=../x64

include $(BGFX_DIR)/scripts/shader.mk
